### ISSUE TITLE
Fix Set ReceiverID example

### ISSUE THREAD

**Issue by boris-gu** [crsf-wg/crsf#10]
https://github.com/crsf-wg/crsf/wiki/CRSF_FRAMETYPE_COMMAND#command_model_select_id

The example shows this package:  
`c8 09 32 ee ea 10 05 14 crc-ba crc`  
The length (pkt[1]) is 9 bytes. But in reality there should be 8 bytes: [32 ee ea 10 05 14 crc-ba crc]

I checked this command by connecting to my rс. The result confirmed that there is an mistake in the wiki:  
`c8 08 32 ee ea 10 05 36 26 a0`

**Comment by CapnBry** [comment]
Ah you're right, thanks! That's what happens when I try to make up an example on the fly. 😳 I've updated the page with your example instead, and added more info about the extra CRC as well.
