### ISSUE TITLE
Physical Layer: define the packet window in half-duplex mode

### ISSUE THREAD

**Issue by wimalopaan** [crsf-wg/crsf#18]
The description of the half-duplex mode mentions the "packet window", but it isn't defined in any section.

**Comment by CapnBry** [comment]
It is quite clear
> Sending channels data, the handset is the master for scheduling when each side can transmit. The handset can transmit at most one packet per interval. Once the external transmitter module completely receives this packet, it can immediately flip to become the transmitter. While it is the transmitter, the external module may transmit as many packets as will fit in the remaining window of the packet period.

The packet period is the interval between the master (handset) sending its one packet. The handset is expected use the interval [requested by the CRSF module](https://github.com/crsf-wg/crsf/wiki/CRSF_FRAMETYPE_RADIO_ID) for its period, but if it doesn't then the period is undefined and nothing is safe.
