### ISSUE TITLE
CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY default value

### ISSUE THREAD

**Issue by ajjjjjjjj** [crsf-wg/crsf#24]
`CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY` types: `INT8/16`, `FLOAT`, `SELECT` are missing default value information, but it is present in `Example SELECT type message` and original TBS lua.

**Comment by wimalopaan** [comment]
Select also misses min and max values
